[workspace]
name = "try_local"
channels = [
    "https://prefix.dev/pixi-build-backends",
    "https://prefix.dev/conda-forge",
    "https://conda.modular.com/max-nightly",
    "https://conda.modular.com/max",
    "https://repo.prefix.dev/modular-community",
    "conda-forge"
]
#platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
platforms = ["linux-64", "osx-arm64", ]
preview = ["pixi-build"]

[dependencies]
max = ">=25.1.0.dev2025020805,<26"

local_lib = { path = "./local_lib" }
demo = { path = "./demo" }


[tasks]

