version: "3"

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

# env file:
#dotenv:
#  - .env

################################################################################################

tasks:
  default:
    cmds:
      - echo 'hello'

  run:0101:
    aliases: [ 'r0101' ]
    cmds:
      - magic run mojo try_01_fn.mojo
    dir: src/0101-intro/

