version: "3"

################################################################################################

tasks:
  fmt:
    cmds:
      - magic run mojo format -l 120 .

  build:pkg:
    aliases: [ 'bp' ]
    cmds:
      - magic run mojo package mypack -o src/mypack.mojopkg

  run:pkg:
    aliases: [ 'rp' ]
    cmds:
      - task: bp
      - magic run mojo src/main.mojo








  pkg:
    aliases: [ 'pm', 'magic' ]
    cmds:
      - magic {{.CLI_ARGS}}
