[project]
authors = ["hhglory <hhglory@outlook.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Add a short description here"
name = "import-local-py"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
numpy = ">=1.26.4,<2"
