version: "3"

includes:
  manual:
    aliases: [ 'm', ]
    taskfile: manual/
    dir: manual/
    optional: true

  dojo:
    taskfile: mojodojo/
    dir: mojodojo/
    optional: true

################################################################################################

tasks:
  default:
    cmds:
      - echo 'hello'
