[tool.poetry]
name = "mojo-manual"
version = "0.1.0"
description = ""
authors = ["Henry.Huang <hhglory@outlook.com>"]
readme = "README.md"
packages = [{ include = "mojo_manual", from = "src" }]


[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"
jupyterlab = "^3.6.3"
notebook = "^6.5.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
