version: "3"

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing
  SRC: "src/mojo_manual"

################################################################################################

tasks:
  run:
    cmds:
      - |
        python3 run.py
    dir: ${SRC}/

  e:
    cmds:
      - modular host-info
      - modular config-list
      - modular --version
      - mojo --version
      - echo $MODULAR_HOME

  r:
    cmds:
      - |
        mojo try_01.mojo
    dir: ${SRC}/

  # run all:
  ra:
    cmds:
      - task: r1
      - task: r2
      - task: r3
      - task: r4
      - task: r5
      - task: r6

  r6:
    cmds:
      - mojo ${SRC}/try_06_traits.mojo

  r5:
    cmds:
      - mojo ${SRC}/try_05_structs.mojo

  r4:
    cmds:
      - mojo ${SRC}/try_04_variables.mojo
      - mojo ${SRC}/try_04b.mojo
      - mojo ${SRC}/try_04c.mojo

  r3:
    cmds:
      - mojo ${SRC}/try_03_fn.mojo
      - mojo ${SRC}/try_03b.mojo
      - mojo ${SRC}/try_03c.mojo

  r2:
    cmds:
      - mojo ${SRC}/try_02.mojo
      - mojo ${SRC}/try_02b.mojo
      - mojo ${SRC}/try_02c.mojo
      - mojo ${SRC}/try_02d.mojo
      - mojo ${SRC}/try_02e.mojo
      - mojo ${SRC}/try_02f.mojo
      - mojo ${SRC}/try_02g.mojo
      - mojo ${SRC}/try_02h_use_py.mojo -I .

  r1:
    cmds:
      - mojo ${SRC}/try_01.mojo

  br1:
    cmds:
      - mkdir build/
      - mojo build ${SRC}/try_01.mojo -o build/main
      - ./build/main
    ignore_error: true

  clean:
    cmds:
      - rm -rf build
      - rm -rf dist
      - mkdir build
      - mkdir dist
    ignore_error: true

  help:
    cmds:
      - mojo build --help

  ################################################################################################

  install:
    cmds:
      - poetry install

  add:
    cmds:
      - poetry add click
      - poetry add jupyterlab notebook

  add:dev:
    cmds:
      - poetry add ${PACKAGE} --dev

  update:
    cmds:
      - poetry update

  config:
    cmds:
      - poetry config virtualenvs.in-project false --local
      - poetry config virtualenvs.create false --local

  env:
    cmds:
      - poetry
      - poetry env list
      - poetry cache list
      - poetry debug info
      - poetry debug resolve
