version: "3"

################################################################################################

tasks:
  default:
    cmds:
      - echo 'hello'

  fmt:
    cmds:
      - magic run mojo format -l 120 .


  build:c:
    aliases: [ 'bc', ]
    cmds:
      - mkdir -p build/
      - cc -shared -fPIC src/clib.c -o build/clib.so
      - cc -c src/clib.c -O -o build/clib.o
    ignore_error: true

  build:
    aliases: [ 'b' ]
    cmds:
      - task: bc # build c lib first
      - magic run mojo src/main.mojo


  clean:
    aliases: [ 'cl', 'del' ]
    cmds:
      - rm -rf build/
    ignore_error: true

  dev:
    aliases: [ 'd', ]
    cmds:
      - magic run mojo src/run.mojo

  r:
    aliases: [ 'run', ]
    cmds:
      - |
        mojo run run.mojo
    dir: "src/"

  r2:
    cmds:
      - .magic/envs/default/bin/mojo run src/run.mojo

  pkg:
    aliases: [ 'pm', 'magic' ]
    cmds:
      - magic {{.CLI_ARGS}}
