version: "3"

################################################################################################

tasks:
  fmt:
    cmds:
      - magic run mojo format -l 120 .

  build:mojo:
    aliases: [ 'bm', 'bmojo' ]
    cmds:
      - mkdir -p build/
      - magic run mojo build src/mojolib.mojo -o build/mojolib.so # -shared

  run:
    aliases: [ 'r' ]
    cmds:
      - task: bm
#      - gcc -L./build -l mojolib.so src/main.c -o build/main
#      - gcc src/main.c -o build/main
      - gcc -L. -l build/mojolib src/main.c -o main
      - ./build/main

  run:mojo:
    aliases: [ 'rm' ]
    cmds:
      - task: gen
      - mkdir -p build/
      - magic run mojo src/main.mojo

  run:c:
    aliases: [ 'rc' ]
    cmds:
      - task: gen
      - mkdir -p build/
      - gcc -c src/main.c -I include -o build/main.o
      - gcc build/main.o -o build/main -L rustlib/target/debug -l rustlib   # 注意相对路径
      - ./build/main
    ignore_error: true

  pkg:
    aliases: [ 'pm', 'magic' ]
    cmds:
      - magic {{.CLI_ARGS}}
