version: "3"



#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

# env file:
#dotenv:
#  - .env

################################################################################################

tasks:
  default:
    cmds:
      - echo 'hello'

  t1:
    cmds:
      - mojo t1_pyobj.mojo

  t2:
    cmds:
      - mojo t2_mojo.mojo

  t3:
    cmds:
      - mojo t3_simd.mojo
