version: "3"

includes:
  try-matplotlib:
    aliases: [ 'tm', ]
    taskfile: try-matplotlib/
    dir: try-matplotlib/
    optional: true

  try-lightbug:
    aliases: [ 'tl', ]
    taskfile: try-lightbug/
    dir: try-lightbug/
    optional: true

################################################################################################

tasks:
  default:
    cmds:
      - echo 'hello'
