[workspace]
name = "demo"
channels = [
    "https://prefix.dev/pixi-build-backends",
    "https://prefix.dev/conda-forge",
    "https://conda.modular.com/max-nightly",
    "https://conda.modular.com/max",
    "https://repo.prefix.dev/modular-community",
    "conda-forge"
]
#platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
platforms = ["linux-64", "osx-arm64", ]
preview = ["pixi-build"]


packages = ["src/main"]



#[project]
#authors = ["hhglory <hhglory@outlook.com>"]
#channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
#description = "Add a short description here"
#name = "demo"
#platforms = ["osx-arm64"]
#version = "0.1.0"

[tasks]

[dependencies]
max = ">=25.1.0.dev2025020805,<26"

local_lib = { path = "../local_lib"}
