version: "3"

################################################################################################

tasks:
  default:
    cmds:
      - echo 'hello'

  r:
    aliases: [ 'run', ]
    cmds:
      - |
        mojo src/run run.mojo


  pkg:
    aliases: [ 'pm', 'magic' ]
    cmds:
      - magic {{.CLI_ARGS}}
