version: "3"

################################################################################################

tasks:
  default:
    cmds:
      - echo 'hello'

  r:
    aliases: [ 'run', ]
    cmds:
      - magic shell
      - mojo run run.mojo
    dir: src/

  pkg:
    aliases: [ 'pm', 'magic' ]
    cmds:
      - magic {{.CLI_ARGS}}
