version: "3"

################################################################################################

tasks:
  default:
    cmds:
      - echo 'hello'

  fmt:
    cmds:
      - magic run mojo format -l 120 .

  gen:rs:c:header:
    aliases: ['gen']
    cmds:
#      - cbindgen --config cbindgen.toml --crate rustlib --output rustlib.h
      - cargo build
      - open target/
    dir: rustlib/

  dev:
    aliases: [ 'd', ]
    cmds:
      - magic run mojo src/run.mojo

  r:
    aliases: [ 'run', ]
    cmds:
      - |
        mojo run run.mojo
    dir: "src/"


  pkg:
    aliases: [ 'pm', 'magic' ]
    cmds:
      - magic {{.CLI_ARGS}}
