version: "3"

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################

tasks:
  run:
    cmds:
      - |
        python3 run.py
    dir: src/mojo101/

  e:
    cmds:
      - modular host-info
      - modular config-list
      - modular --version
      - mojo --version
      - echo $MODULAR_HOME

  r:
    cmds:
      - |
        mojo try_01.mojo
    dir: src/mojo101/

  r2:
    cmds:
      - mojo src/mojo101/try_02.mojo
      - mojo src/mojo101/try_02b.mojo
      - mojo src/mojo101/try_02c.mojo
      - mojo src/mojo101/try_02d.mojo
      - mojo src/mojo101/try_02e.mojo
      - mojo src/mojo101/try_02f.mojo
      - mojo src/mojo101/try_02g.mojo
      - mojo src/mojo101/try_02h_use_py.mojo -I .

  r1:
    cmds:
      - mojo src/mojo101/try_01.mojo

  br1:
    cmds:
      - mkdir build/
      - mojo build src/mojo101/try_01.mojo -o build/main
      - ./build/main
    ignore_error: true

  run2:
    cmds:
      - mojo run try_trait.mojo
    dir: src/mojo101/

  build:
    cmds:
      - mkdir build/
      - mojo build src/mojo101/try_trait.mojo -o build/main
    ignore_error: true

  b:
    cmds:
      - task: build

  br:
    cmds:
      - task: build
      - ./build/main

  clean:
    cmds:
      - rm -rf build
      - rm -rf dist
      - mkdir build
      - mkdir dist
    ignore_error: true

  help:
    cmds:
      - mojo build --help

  ################################################################################################

  install:
    cmds:
      - poetry install

  add:
    cmds:
      - poetry add click
      - poetry add jupyterlab notebook

  add:dev:
    cmds:
      - poetry add ${PACKAGE} --dev

  update:
    cmds:
      - poetry update

  config:
    cmds:
      - poetry config virtualenvs.in-project false --local
      - poetry config virtualenvs.create false --local

  env:
    cmds:
      - poetry
      - poetry env list
      - poetry cache list
      - poetry debug info
      - poetry debug resolve
