version: "3"

includes:
  import-pkg:
    aliases: [ 'ip', 'pkg' ]
    taskfile: import-pkg/
    dir: import-pkg/
    optional: true

################################################################################################

tasks:
  default:
    cmds:
      - echo 'hello'
